setwd("C:/Users/lavis/OneDrive/Documents/R/R_Project/R Dashboards")
#creating a data frame
df <- read.csv('~/R/R_Project/R Dashboards/Netflixdas_22it473/Netflix_Userbase.csv')
View(df)

#color palatte
colors <- c('#221f1f', '#b20710', '#e50914', '#f5f5f1')

# histogram for age based users
hist(df$Age,
     main="Most Userbase according to Age",
     xlab="Age",
     ylab=" ",
     col=colors,
     breaks=5,
     ylim = c(0,570))

# 3D pie chart for subscription
library(plotrix)
library(dplyr)
subc <- data.frame( df %>% 
  group_by(df$SubscriptionType) %>% 
  summarise(count = n()))
pie3D(subc$count,labels = subc$df.SubscriptionType,
      explode=0.05,main="Pie Chart of Subscription Type",
      col = colors,theta = pi/4,radius = 0.85, height = 0.15)

# bar plot based on the devices used
devicecount <- data.frame( df %>% 
                      group_by(df$Device) %>% 
                      summarise(count = n()))
barplot(devicecount$count, names.arg = devicecount$df.Device,
        col = colors, 
        main = "Application operated on Devices", 
        xlab = "Devices", 
        ylab = " ", 
        ylim = c(0, 700))

# stacked bar chart based on Country Gender Population Counts 
library(ggplot2)
cgstck <- data.frame(df %>%
  group_by(df$Country,df$Gender) %>%
  summarise(count = n()))
ggplot(cgstck, aes(x = cgstck$df.Country,
                   y = cgstck$count, fill = cgstck$df.Gender)) +
  geom_bar(stat = "identity", position = "stack",width = 0.7) + 
  xlab("Country")+ ylab("Count") + 
  theme_classic() + labs(fill = "Gender") + 
  ggtitle("Country Gender Population Counts") +
  scale_fill_manual(values = c('#e50914', '#221f1f'))
  #classic theme removes the grid

# graph to understand the revenue generated by various subscriptions
mr_sub <- df %>%
          group_by(df$SubscriptionType) %>%
          summarise(count = n())
pie(mr_sub$count,labels = mr_sub$`df$SubscriptionType`,
    radius = 1.0,col = colors , angle = 45 ,edges = 500 ,
    clockwise = TRUE,
    main="Revenue from different Subscriptions")

# plot for revenue generated from country
mr_coun <- df %>%
           group_by(df$Country) %>%
           summarise(revcount = n())
ggplot(mr_coun , aes(x = mr_coun$revcount,
                     y = mr_coun$`df$Country`)) +
  geom_jitter()+   
  ggtitle("Revenue each Country generates") +
  theme_minimal()+ ylab("Country")+ xlab(" ")

#total revenue
totr <- sum(df$MonthlyRevenue)
